/**
 * This code was generated by Builder.io
 */

{
  /* <FILE path="NutritionistComponents/BlogsSection.tsx"> */
}
import React from "react";

interface BlogCardProps {
  image: string;
  category: string;
  title: string;
  description: string;
  author: {
    image: string;
    name: string;
    date: string;
  };
}

const BlogCard: React.FC<BlogCardProps> = ({
  image,
  category,
  title,
  description,
  author,
}) => (
  <article
    data-layername="card"
    className="flex flex-col flex-1 shrink basis-0 min-w-[240px] max-md:max-w-full"
  >
    <div className="flex flex-col justify-center p-10 w-full bg-lime-50 rounded-xl border border-lime-100 border-solid max-md:px-5 max-md:max-w-full">
      <img
        loading="lazy"
        src={image}
        alt={title}
        className="object-contain w-full rounded-xl aspect-[1.64] max-md:max-w-full"
      />
      <div
        data-layername="container"
        className="flex flex-col mt-10 w-full max-md:max-w-full"
      >
        <div className="flex flex-col w-full max-md:max-w-full">
          <div
            data-layername="text"
            className="text-lg font-medium text-zinc-800 max-md:max-w-full"
          >
            {category}
          </div>
          <h3
            data-layername="heading"
            className="mt-1 text-2xl font-semibold text-neutral-800 max-md:max-w-full"
          >
            {title}
          </h3>
        </div>
        <p
          data-layername="paragraph"
          className="mt-8 text-lg font-medium leading-7 text-neutral-600 max-md:max-w-full"
        >
          {description}
        </p>
        <div
          data-layername="subContainer"
          className="flex flex-wrap gap-5 items-center py-5 pr-4 pl-5 mt-8 w-full rounded-xl border border-lime-100 border-solid bg-stone-50 max-md:max-w-full"
        >
          <div
            data-layername="container"
            className="flex flex-wrap flex-1 shrink gap-4 items-center self-stretch my-auto basis-0 min-w-[240px] max-md:max-w-full"
          >
            <img
              loading="lazy"
              src={author.image}
              alt={author.name}
              className="object-contain shrink-0 self-stretch my-auto rounded-lg aspect-square w-[60px]"
            />
            <div className="flex flex-col flex-1 shrink self-stretch my-auto basis-0 min-w-[240px] max-md:max-w-full">
              <div
                data-layername="name"
                className="text-xl font-semibold text-zinc-800 max-md:max-w-full"
              >
                {author.name}
              </div>
              <div
                data-layername="text"
                className="text-lg font-medium text-zinc-600 max-md:max-w-full"
              >
                {author.date}
              </div>
            </div>
          </div>
          <div
            data-layername="container"
            className="flex gap-2.5 items-start self-stretch my-auto"
          >
            <button
              data-layername="iconContainer"
              className="flex gap-2.5 items-center p-5 bg-lime-50 rounded-lg border border-lime-100 border-solid h-[60px] w-[60px]"
              aria-label="Share"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/115c54d766401cb96bd99f4172b8b54f1aa7e310d6e939f02d583767897f8153?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
                alt=""
                className="object-contain w-6 aspect-square"
              />
            </button>
            <button
              data-layername="iconContainer"
              className="flex gap-2.5 items-center p-5 bg-lime-50 rounded-lg border border-lime-100 border-solid h-[60px] w-[60px]"
              aria-label="Like"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/b44153a47d00b433f67aa56df76d9cf2abc57aca271af89e1afa956dea7f6585?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
                alt=""
                className="object-contain w-6 aspect-square"
              />
            </button>
          </div>
        </div>
      </div>
    </div>
  </article>
);

const BlogsSection: React.FC = () => {
  const blogs = [
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/0febf58b92d061cf3220b2255b9c88a423104cfcdfd5b658f6b16c2cb5b7ad45?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      category: "Weight Loss",
      title: "The Benefits of Hydration for Weight Loss",
      description:
        "Discover how staying hydrated can support your weight loss goals and improve overall health.",
      author: {
        image:
          "https://cdn.builder.io/api/v1/image/assets/TEMP/f5c042fdd30a68f8c1f0929ca88de98c866cf255d4f4dce504657289f8e0c054?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
        name: "Emily Johnson",
        date: "23 May 2023 - 5 min read",
      },
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/4c625c603f63d93462c00f2044fbbae29371a6c0e10434212377555493130c29?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      category: "Understanding Macronutrients",
      title: "Carbohydrates, Proteins, and Fats",
      description:
        "Get a comprehensive understanding of macronutrients and their role in your diet for optimal health and weight management.",
      author: {
        image:
          "https://cdn.builder.io/api/v1/image/assets/TEMP/9cb91c627e2e0d9be8d398dc2b3005758624c4322857f181757707f233f409dc?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
        name: "Mark Wilson",
        date: "23 May 2023 - 5 min read",
      },
    },
  ];

  return (
    <section
      data-layername="blogsSection"
      className="flex flex-col mt-44 w-full max-w-[1596px] max-md:mt-10 max-md:max-w-full"
    >
      <div className="flex flex-col px-72 w-full text-center max-md:px-5 max-md:max-w-full">
        <h2
          data-layername="heading"
          className="text-5xl font-bold text-neutral-800 max-md:max-w-full max-md:text-4xl"
        >
          Our Blogs
        </h2>
        <p
          data-layername="paragraph"
          className="mt-2.5 text-lg font-medium leading-7 text-zinc-800 max-md:max-w-full"
        >
          Our blog is a treasure trove of informative and engaging articles
          written by our team of nutritionists, dietitians, and wellness
          experts. Here's what you can expect from our blog.
        </p>
      </div>
      <div
        data-layername="container"
        className="flex flex-wrap gap-8 items-start mt-20 w-full max-md:mt-10 max-md:max-w-full"
      >
        {blogs.map((blog, index) => (
          <BlogCard key={index} {...blog} />
        ))}
      </div>
    </section>
  );
};

export default BlogsSection;
