/**
 * This code was generated by Builder.io
 */
import React from "react";

interface FeatureCardProps {
  icon: string;
  title: string;
  description: string;
}

const FeatureCard: React.FC<FeatureCardProps> = ({
  icon,
  title,
  description,
}) => (
  <div
    data-layername="card"
    className="flex flex-col flex-1 shrink px-12 py-10 bg-lime-50 rounded-xl border border-lime-100 border-solid basis-0 min-w-[240px] max-md:px-5 max-md:max-w-full"
  >
    <div
      data-layername="container"
      className="flex flex-wrap gap-3.5 items-center w-full max-md:max-w-full"
    >
      <div
        data-layername="iconContainer"
        className="flex gap-2.5 items-center self-stretch p-3.5 my-auto bg-lime-300 rounded-lg h-[68px] w-[68px]"
      >
        <img
          loading="lazy"
          src={icon}
          alt=""
          className="object-contain w-10 aspect-square"
        />
      </div>
      <h3
        data-layername="heading"
        className="flex-1 shrink self-stretch my-auto text-2xl font-semibold basis-7 text-neutral-800 max-md:max-w-full"
      >
        {title}
      </h3>
    </div>
    <p
      data-layername="paragraph"
      className="mt-6 text-lg font-medium leading-7 text-zinc-800 max-md:max-w-full"
    >
      {description}
    </p>
  </div>
);

const FeaturesSection: React.FC = () => {
  const features = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/802fdc30ee12b65770db7b57454ab362858fb694ec48ac95e9f5c67a1fd6f0ba?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      title: "Personalized Nutrition Plans",
      description:
        "Receive a tailored nutrition plan designed specifically for your body and goals. Our certified nutritionists will consider your unique needs, dietary preferences, and health conditions to create a plan that suits you best.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/384bd2139c9f37d2906ab191a30337ccc4807cfaad71d55386b96c517340f14a?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      title: "Guidance from Certified Nutritionists",
      description:
        "Our team of experienced and certified nutritionists will provide professional guidance and support throughout your journey. They will answer your questions, address your concerns, and keep you motivated as you work towards your goals.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/443115821ad7b0fe5f1b5affff5da92b0cd2adcdfe5dc47feb9c6b85ff07c9a7?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      title: "Food Tracking and Analysis",
      description:
        "Effortlessly track your food intake using our user-friendly app. Our nutritionists will analyze your data to provide insights into your eating habits, help you identify areas for improvement, and make personalized recommendations.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/31766eb2e412186363220e96802990cd09dd996b99c1838773c74a120ad9b3f5?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      title: "Meal Planning and Recipes",
      description:
        "Access a vast collection of delicious and healthy recipes tailored to your dietary needs. Our nutritionists will also create personalized meal plans, making it easier for you to stay on track and enjoy nutritious meals.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/5909d24bf3939530a9f9cdd1d7f6fbd7b52d8d2f5be9db9cd2416ab69f6d8cde?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      title: "Lifestyle and Behavior Coaching",
      description:
        "Achieving sustainable results requires more than just a diet plan. Our nutritionists will work with you to develop healthy habits, address emotional eating, and provide strategies to overcome obstacles along the way.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/18f6a78cde1506007400daa8136cfe7815f820d88d1637a365316c2de6a7798c?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      title: "Nutritional Education and Workshops",
      description:
        "Expand your knowledge of nutrition through informative articles and educational workshops. Our nutritionists will equip you with the knowledge and tools to make informed choices for long-term success.",
    },
  ];

  return (
    <section
      data-layername="featuresSection"
      className="flex flex-col mt-36 w-full max-w-[1596px] max-md:mt-10 max-md:max-w-full"
    >
      <div className="flex flex-col px-72 w-full text-center max-md:px-5 max-md:max-w-full">
        <h2
          data-layername="heading"
          className="text-5xl font-bold text-neutral-800 max-md:max-w-full max-md:text-4xl"
        >
          Features
        </h2>
        <p
          data-layername="paragraph"
          className="mt-2.5 text-lg font-medium text-zinc-800 max-md:max-w-full"
        >
          Welcome to the Feature Section of Nutritionist, your ultimate
          destination for all things nutrition and wellness.
        </p>
      </div>
      <div
        data-layername="container"
        className="flex flex-col mt-20 w-full max-md:mt-10 max-md:max-w-full"
      >
        <div
          data-layername="subContainer"
          className="flex flex-wrap gap-8 items-start w-full max-md:max-w-full"
        >
          {features.slice(0, 2).map((feature, index) => (
            <FeatureCard key={index} {...feature} />
          ))}
        </div>
        <div
          data-layername="subContainer"
          className="flex flex-wrap gap-8 items-start mt-8 w-full max-md:max-w-full"
        >
          {features.slice(2, 4).map((feature, index) => (
            <FeatureCard key={index + 2} {...feature} />
          ))}
        </div>
        <div
          data-layername="subContainer"
          className="flex flex-wrap gap-8 items-start mt-8 w-full max-md:max-w-full"
        >
          {features.slice(4, 6).map((feature, index) => (
            <FeatureCard key={index + 4} {...feature} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default FeaturesSection;
