/**
 * This code was generated by Builder.io
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <footer
      data-layername="footerSection"
      className="flex flex-col self-stretch px-40 py-12 mt-36 w-full border-t border-solid bg-zinc-800 border-t-neutral-800 max-md:px-5 max-md:mt-10 max-md:max-w-full"
    >
      <div
        data-layername="container"
        className="flex relative justify-between items-center w-full max-md:max-w-full"
      >
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/fc84d0d3afc60b74253ad34bc8b532017ab543762e63730ae4a25f94c679e56e?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
          alt="Nutritionist Logo"
          className="object-contain z-0 shrink-0 self-stretch my-auto aspect-[4.33] w-[195px]"
        />
        <div
          data-layername="subContainer"
          className="flex z-0 gap-5 items-center self-stretch my-auto rounded-xl"
        >
          <div
            data-layername="text"
            className="self-stretch my-auto text-lg font-semibold text-white"
          >
            Go To Top
          </div>
          <button
            data-layername="button"
            className="flex flex-col justify-center items-center self-stretch px-3.5 my-auto bg-green-900 h-[62px] rounded-[73px] w-[62px]"
            aria-label="Go to top"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/b984daaa947cae47079c98c7233907b9f9a35b715e080313f94d43a4d4ccfb24?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
              alt=""
              className="object-contain aspect-square w-[34px]"
            />
          </button>
        </div>
        <nav
          data-layername="buttonsContainer"
          className="flex absolute top-2/4 left-2/4 z-0 flex-wrap gap-7 items-center self-start text-lg font-semibold text-white whitespace-nowrap -translate-x-2/4 -translate-y-2/4 min-w-[240px] max-md:max-w-full"
        >
          <a href="#" className="self-stretch my-auto">
            Home
          </a>
          <a href="#" className="self-stretch my-auto">
            About
          </a>
          <a href="#" className="self-stretch my-auto">
            Team
          </a>
          <a href="#" className="self-stretch my-auto">
            Process
          </a>
          <a href="#" className="self-stretch my-auto">
            Pricing
          </a>
          <a href="#" className="self-stretch my-auto">
            Blog
          </a>
          <a href="#" className="self-stretch my-auto">
            Contact
          </a>
        </nav>
      </div>
      <div
        data-layername="container"
        className="flex flex-wrap gap-10 justify-between items-center py-4 pr-8 pl-5 mt-12 w-full text-lg bg-green-900 rounded-lg border border-gray-700 border-solid max-md:pr-5 max-md:mt-10 max-md:max-w-full"
      >
        <div
          data-layername="subContainer"
          className="flex flex-wrap gap-5 items-start self-stretch my-auto font-medium text-white min-w-[240px] max-md:max-w-full"
        >
          <a
            href="mailto:hello@squareup.com"
            data-layername="button"
            className="flex gap-1.5 items-center p-3.5 whitespace-nowrap rounded-md border border-gray-700 border-solid"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/dd80754d59ecafe47605e08b7cf2da709be8ce89743ecd37635b28590ea062bc?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
            />
            <div className="self-stretch my-auto">hello@squareup.com</div>
          </a>
          <a
            href="tel:+919181323230"
            data-layername="button"
            className="flex gap-1.5 items-center p-3.5 rounded-md border border-gray-700 border-solid"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/79a791a59734258aa73037e3b9a8c71dff93229d2044b7fec60c07a3bb19a744?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
            />
            <div className="self-stretch my-auto">+91 91813 23 2309</div>
          </a>
          <div
            data-layername="button"
            className="flex gap-1.5 items-center p-3.5 rounded-md border border-gray-700 border-solid min-w-[240px]"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/b5a77779ad27c1b4d987d98e83e11d4145d03e5916065d159fb786ece12d9005?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
            />
            <div className="self-stretch my-auto">Somewhere in the World</div>
          </div>
        </div>
        <div
          data-layername="text"
          className="self-stretch my-auto text-zinc-100"
        >
          © 2023 Nutritionist. All rights reserved.
        </div>
      </div>
    </footer>
  );
};

export default Footer;
