/**
 * This code was generated by Builder.io
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header
      data-layername="header"
      className="flex flex-col self-stretch w-full text-lg max-md:max-w-full"
    >
      <div
        data-layername="topBanner"
        className="flex flex-col justify-center px-40 py-3.5 w-full font-medium text-white border-b border-solid bg-zinc-800 border-b-green-900 max-md:px-5 max-md:max-w-full"
      >
        <div
          data-layername="container"
          className="flex overflow-hidden relative flex-wrap gap-5 justify-center items-start px-5 py-2.5 w-full bg-green-900 rounded-md border border-gray-700 border-solid max-md:max-w-full"
        >
          <div
            data-layername="subContainer"
            className="flex z-0 gap-1.5 items-center my-auto min-w-[240px]"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d1c1b33679c2fa8674a722fa8a0f59f2ed2b496936d70a4205d3a608496228b7?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
            />
            <div data-layername="text">
              Join Our Personalized Nutrition Demo For Free
            </div>
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a810f1efc883567d2d8f19b621128259a8076793e80e20ba1ae80376118a37c8?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
            alt=""
            className="object-contain z-0 shrink-0 my-auto w-6 aspect-square"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/6bc2e707430b11190927d1cebbe50aa3c72fe44bcf5c03069b3e92dc912814a8?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
            alt=""
            className="object-contain absolute left-10 top-2/4 z-0 shrink-0 self-start -translate-y-2/4 aspect-[4.41] h-[100px] translate-x-[0%] w-[194px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/5e4f152b3ff3249284029043a08e5e27df03f1cb5f76216417acc17d760edd52?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
            alt=""
            className="object-contain absolute right-10 top-2/4 z-0 shrink-0 self-start -translate-y-2/4 aspect-[4.41] h-[100px] translate-x-[0%] w-[194px]"
          />
        </div>
      </div>
      <nav
        data-layername="navbar"
        className="flex flex-wrap gap-10 justify-between items-center px-40 py-5 w-full font-semibold border-b border-solid bg-zinc-800 border-b-lime-100 max-md:px-5 max-md:max-w-full"
      >
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/51baaa1c6ac4872d6e859323eb2e1a0e1bcaa454526e4c092f797070dd030c5d?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
          alt="Nutritionist Logo"
          className="object-contain shrink-0 self-stretch my-auto aspect-[4.33] w-[195px]"
        />
        <div
          data-layername="container"
          className="flex flex-wrap gap-10 items-center self-stretch my-auto min-w-[240px] max-md:max-w-full"
        >
          <div
            data-layername="buttonsContainer"
            className="flex gap-7 items-center self-stretch my-auto whitespace-nowrap min-w-[240px] text-stone-50 max-md:max-w-full"
          >
            <a href="#" className="self-stretch my-auto text-lime-300">
              Home
            </a>
            <a href="#" className="self-stretch my-auto">
              About
            </a>
            <a href="#" className="self-stretch my-auto">
              Team
            </a>
            <a href="#" className="self-stretch my-auto">
              Process
            </a>
            <a href="#" className="self-stretch my-auto">
              Pricing
            </a>
            <a href="#" className="self-stretch my-auto">
              Blog
            </a>
          </div>
          <button
            data-layername="button"
            className="gap-2 self-stretch px-6 py-3.5 my-auto bg-lime-300 rounded-lg text-neutral-800 max-md:px-5"
          >
            Contact Us
          </button>
        </div>
      </nav>
    </header>
  );
};

export default Header;
