/**
 * This code was generated by Builder.io
 */
import React from "react";

const HeroSection: React.FC = () => {
  return (
    <section
      data-layername="heroSection"
      className="flex z-10 flex-wrap gap-10 items-center self-stretch pr-40 w-full max-md:pr-5 max-md:max-w-full"
    >
      {" "}
      <div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/5de5fcae448fc1db4803575f0664415cd27cdc235c9bc60cb5cd386d9281956f?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
          alt="Nutritionist hero image"
          className="object-contain self-stretch my-auto rounded-none aspect-[1.14] min-w-[240px] w-[949px] max-md:max-w-full"
        />
      </div>
      <div
        data-layername="container"
        className="flex flex-col flex-1 shrink self-stretch my-auto basis-0 min-w-[240px] max-md:max-w-full"
      >
        <div
          data-layername="subContainer"
          className="flex flex-col w-full max-md:max-w-full"
        >
          <div
            data-layername="container"
            className="flex flex-col w-full max-md:max-w-full"
          >
            <div
              data-layername="subContainer"
              className="flex flex-col w-full text-zinc-800 max-md:max-w-full"
            >
              <div
                data-layername="container"
                className="gap-2.5 self-start py-2.5 text-3xl font-semibold border-solid border-b-[3px] border-b-lime-300"
              >
                Transform Your ❤️ Health with
              </div>
              <h1
                data-layername="heading"
                className="mt-3.5 text-6xl font-bold max-md:max-w-full max-md:text-4xl"
              >
                Personalized Nutrition Coaching
              </h1>
            </div>
            <p
              data-layername="paragraph"
              className="mt-5 text-lg font-medium leading-7 text-zinc-800 max-md:max-w-full"
            >
              Welcome to Nutritionist, your partner in achieving optimal health
              through personalized nutrition coaching. Our certified
              nutritionists are here to guide you on your weight loss journey,
              providing customized plans and ongoing support. Start your
              transformation today and experience the power of personalized
              nutrition coaching.
            </p>
          </div>
          <div
            data-layername="buttonsContainer"
            className="flex gap-5 items-start self-start mt-12 text-lg font-semibold text-neutral-800 max-md:mt-10"
          >
            <button
              data-layername="button"
              className="gap-2 self-stretch px-5 py-4 bg-lime-300 rounded-lg"
            >
              Get Started Today
            </button>
            <button
              data-layername="button"
              className="gap-2 self-stretch px-6 py-4 bg-lime-50 rounded-lg border border-lime-100 border-solid max-md:px-5"
            >
              Book a Demo
            </button>
          </div>
        </div>
        <div
          data-layername="subContainer"
          className="flex flex-wrap gap-2 items-center mt-16 w-full max-md:mt-10 max-md:max-w-full"
        >
          <div
            data-layername="container"
            className="flex gap-0 items-center self-stretch px-2.5 py-2 my-auto border border-lime-300 border-solid rounded-[58px]"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/7c839a4d0aeab5ad9998ec8306818d38bb3ce6ec370c2369ee2786f4aeb4f874?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
              alt="Happy customer 1"
              className="object-contain shrink-0 self-stretch my-auto aspect-square rounded-[53px] w-[50px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/4df3be897c943ef6089ea74ba30ef999d7bb147a82290e0b4865754f63e73c9c?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
              alt="Happy customer 2"
              className="object-contain shrink-0 self-stretch my-auto aspect-square rounded-[53px] w-[50px]"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/3e553eed193c8aa00c3cdb2e55ce6cd8b57122ee452e191b68cd8659fa4ef630?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
              alt="Happy customer 3"
              className="object-contain shrink-0 self-stretch my-auto aspect-square rounded-[53px] w-[50px]"
            />
          </div>
          <div
            data-layername="text"
            className="self-stretch my-auto text-xl font-semibold text-green-900"
          >
            <span className="font-bold text-slate-500">430+</span>{" "}
            <span className="text-green-900">Happy Customers</span>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
