/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import HeroSection from "./HeroSection";
import FeaturesSection from "./FeaturesSection";
import BlogsSection from "./BlogsSection";
import TestimonialsSection from "./TestimonialsSection";
import PricingSection from "./PricingSection";
import Footer from "./Footer";

const NutritionistApp: React.FC = () => {
  return (
    <div
      data-layername="homePageDesktop"
      className="flex flex-col items-center overflow-hidden bg-stone-50"
    >
      {/* <Header /> */}
      {/* <HeroSection /> */}
      {/* <FeaturesSection /> */}
      <BlogsSection />
      <TestimonialsSection />
      <PricingSection />
      <Footer />
    </div>
  );
};

export default NutritionistApp;
