/**
 * This code was generated by Builder.io
 */
"use client";
import React, { useState } from "react";

interface PricingPlanProps {
  title: string;
  description: string;
  price: string;
  isYearly: boolean;
}

const PricingPlan: React.FC<PricingPlanProps> = ({
  title,
  description,
  price,
  isYearly,
}) => (
  <div
    data-layername="card"
    className="flex flex-col flex-1 shrink p-12 bg-lime-50 rounded-xl border border-lime-100 border-solid basis-0 min-w-[240px] max-md:px-5 max-md:max-w-full"
  >
    <div className="flex flex-col w-full">
      <h3
        data-layername="heading"
        className="text-3xl font-semibold text-neutral-800"
      >
        {title}
      </h3>
      <div
        data-layername="text"
        className="text-lg font-medium text-neutral-600"
      >
        Up to 50% off on Yearly Plan
      </div>
    </div>
    <p
      data-layername="paragraph"
      className="mt-10 text-lg font-medium leading-7 text-neutral-800"
    >
      {description}
    </p>
    <div data-layername="container" className="flex flex-col mt-10 w-full">
      <div
        data-layername="subContainer"
        className="flex gap-1 justify-center items-center self-start whitespace-nowrap"
      >
        <div
          data-layername="number"
          className="self-stretch my-auto text-5xl font-bold leading-none text-gray-700 max-md:text-4xl"
        >
          {price}
        </div>
        <div
          data-layername="text"
          className="self-stretch my-auto text-lg font-medium text-zinc-800"
        >
          /{isYearly ? "year" : "month"}
        </div>
      </div>
      <button
        data-layername="button"
        className="gap-2.5 self-stretch px-10 py-5 mt-8 w-full text-lg font-semibold bg-lime-300 rounded-lg text-neutral-800 max-md:px-5"
      >
        Choose Plan
      </button>
    </div>
  </div>
);

const PricingSection: React.FC = () => {
  const [isYearly, setIsYearly] = useState(false);

  const plans = [
    {
      title: "Basic Plan",
      description:
        "Get started on your health journey with our Basic Plan. It includes personalized nutrition coaching, access to our app, meal planning assistance, and email support.",
      price: isYearly ? "$490" : "$49",
    },
    {
      title: "Premium Plan",
      description:
        "Upgrade to our Premium Plan for enhanced features. In addition to the Basic Plan, you'll receive video consultations, priority support, and personalized recipe recommendations.",
      price: isYearly ? "$790" : "$79",
    },
    {
      title: "Ultimate Plan",
      description:
        "Experience the full benefits of personalized nutrition coaching with our Ultimate Plan. Enjoy all the features of the Premium Plan, along with 24/7 chat support and exclusive workshops.",
      price: isYearly ? "$990" : "$99",
    },
  ];

  return (
    <section
      data-layername="pricingSection"
      className="flex flex-col mt-44 w-full max-w-[1596px] max-md:mt-10 max-md:max-w-full"
    >
      <div className="flex flex-col px-72 w-full text-center max-md:px-5 max-md:max-w-full">
        <h2
          data-layername="heading"
          className="text-5xl font-bold text-neutral-800 max-md:max-w-full max-md:text-4xl"
        >
          Our Pricing
        </h2>
        <p
          data-layername="paragraph"
          className="mt-2.5 text-lg font-medium leading-7 text-zinc-800 max-md:max-w-full"
        >
          We outline our flexible and affordable options to support you on your
          journey to optimal health and nutrition. We believe that everyone
          deserves access to personalized nutrition guidance and resources
        </p>
      </div>
      <div
        data-layername="contentContainer"
        className="flex flex-col mt-20 w-full max-md:mt-10 max-md:max-w-full"
      >
        <div
          data-layername="container"
          className="flex flex-col self-center max-w-full text-lg w-[311px]"
        >
          <div
            data-layername="tabs"
            className="flex items-center self-center p-2.5 font-semibold whitespace-nowrap rounded-lg border border-lime-200 border-solid"
          >
            <button
              data-layername="buttonActive"
              className={`gap-2.5 self-stretch px-6 py-2.5 my-auto rounded-md ${
                !isYearly ? "text-white bg-green-900" : "text-neutral-600"
              } max-md:px-5`}
              onClick={() => setIsYearly(false)}
            >
              Monthly
            </button>
            <button
              data-layername="button"
              className={`gap-2.5 self-stretch px-6 py-2.5 my-auto rounded-[100px] ${
                isYearly ? "text-white bg-green-900" : "text-neutral-600"
              } max-md:px-5`}
              onClick={() => setIsYearly(true)}
            >
              Yearly
            </button>
          </div>
          <div
            data-layername="text"
            className="mt-3.5 font-medium text-center text-neutral-600"
          >
            Save 50% on Yearly
          </div>
        </div>
        <div
          data-layername="container"
          className="flex flex-wrap gap-8 items-start mt-12 w-full max-md:mt-10 max-md:max-w-full"
        >
          {plans.map((plan, index) => (
            <PricingPlan key={index} {...plan} isYearly={isYearly} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default PricingSection;
