/**
 * This code was generated by Builder.io
 */
import React from "react";

interface TestimonialCardProps {
  content: string;
  author: {
    name: string;
    image: string;
  };
}

const TestimonialCard: React.FC<TestimonialCardProps> = ({
  content,
  author,
}) => (
  <div
    data-layername="card"
    className="flex overflow-hidden flex-col flex-1 shrink rounded-xl border border-lime-100 border-solid basis-0 bg-stone-50 min-w-[240px] max-md:max-w-full"
  >
    <div
      data-layername="container"
      className="flex flex-col p-10 w-full font-medium leading-7 rounded-2xl text-zinc-800 max-md:px-5 max-md:max-w-full"
    >
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d9b3e280394572de1f4fcf03b108c24cb781ceab79312145a319f36f17c663ff?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
        alt=""
        className="object-contain w-10 aspect-square"
      />
      <p
        data-layername="paragraph"
        className="mt-12 max-md:mt-10 max-md:max-w-full"
      >
        {content}
      </p>
    </div>
    <div
      data-layername="line"
      className="w-full bg-lime-100 border border-lime-100 border-solid min-h-[1px] max-md:max-w-full"
    />
    <div
      data-layername="container"
      className="flex flex-wrap gap-3 items-center px-10 py-8 w-full font-semibold bg-lime-50 text-zinc-800 max-md:px-5 max-md:max-w-full"
    >
      <img
        loading="lazy"
        src={author.image}
        alt={author.name}
        className="object-contain shrink-0 self-stretch my-auto rounded-lg aspect-square w-[60px]"
      />
      <div
        data-layername="name"
        className="flex-1 shrink self-stretch my-auto basis-0"
      >
        {author.name}
      </div>
    </div>
  </div>
);

const TestimonialsSection: React.FC = () => {
  const testimonials = [
    {
      content:
        "I can't thank Nutritionist enough for their personalized nutrition coaching. It has completely transformed my approach to food and helped me shed those extra pounds. Highly recommended!",
      author: {
        name: "Jennifer Anderson",
        image:
          "https://cdn.builder.io/api/v1/image/assets/TEMP/b89a9eb3bc7cbab1b73138fa414beac907a0fa34ad079624940934d406ec4c61?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      },
    },
    {
      content:
        "Nutritionist has been a game-changer for me. The expert guidance and support I received from their team made my weight loss journey so much easier. Thank you!",
      author: {
        name: "Robert Johnson",
        image:
          "https://cdn.builder.io/api/v1/image/assets/TEMP/abfac095c26beb2348905364134834bf5428b987880d23f26709026ff3def456?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      },
    },
    {
      content:
        "I had struggled with my weight for years until I found Nutritionist. Their personalized approach and tailored nutrition plan made all the difference. I've never felt better!",
      author: {
        name: "Emily Davis",
        image:
          "https://cdn.builder.io/api/v1/image/assets/TEMP/d853d84767dfabff9304fed760c00c3a8aefdb0e4a305925173da5201c2333f7?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      },
    },
  ];

  return (
    <section
      data-layername="testimonialsSection"
      className="flex flex-col mt-36 w-full max-w-[1596px] max-md:mt-10 max-md:max-w-full"
    >
      <div className="flex flex-col px-72 w-full text-center max-md:px-5 max-md:max-w-full">
        <h2
          data-layername="heading"
          className="text-5xl font-bold text-neutral-800 max-md:max-w-full max-md:text-4xl"
        >
          Our Testimonials
        </h2>
        <p
          data-layername="paragraph"
          className="mt-2.5 text-lg font-medium text-zinc-800 max-md:max-w-full"
        >
          Our satisfied clients share their success stories and experiences on
          their journey to better health and well-being.
        </p>
      </div>
      <div
        data-layername="container"
        className="flex flex-col mt-20 w-full max-md:mt-10 max-md:max-w-full"
      >
        <div
          data-layername="itemsContainer"
          className="flex flex-wrap gap-5 items-start w-full text-lg max-md:max-w-full"
        >
          {testimonials.map((testimonial, index) => (
            <TestimonialCard key={index} {...testimonial} />
          ))}
        </div>
        <div
          data-layername="buttonsContainer"
          className="flex flex-wrap gap-8 justify-center items-center mt-12 w-full max-md:mt-10 max-md:max-w-full"
        >
          <button
            data-layername="button"
            className="flex gap-2.5 items-center self-stretch p-3 my-auto bg-lime-50 rounded-lg border border-lime-100 border-solid h-[58px] w-[58px]"
            aria-label="Previous testimonial"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/b3664d9f021538ecff558b007edc3ee66d446fc65606fd7d5d252d9640c33335?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
              alt=""
              className="object-contain aspect-square w-[34px]"
            />
          </button>
          <div
            data-layername="indicators"
            className="flex gap-1 items-start self-stretch my-auto"
          >
            <div
              data-layername="shape"
              className="flex shrink-0 w-2 h-2 bg-gray-600 rounded-full fill-gray-600"
            />
            <div
              data-layername="shape"
              className="flex shrink-0 w-2 h-2 bg-lime-100 rounded-full fill-lime-100"
            />
            <div
              data-layername="shape"
              className="flex shrink-0 w-2 h-2 bg-lime-100 rounded-full fill-lime-100"
            />
            <div
              data-layername="shape"
              className="flex shrink-0 w-2 h-2 bg-lime-100 rounded-full fill-lime-100"
            />
            <div
              data-layername="shape"
              className="flex shrink-0 w-2 h-2 bg-lime-100 rounded-full fill-lime-100"
            />
          </div>
          <button
            data-layername="button"
            className="flex gap-2.5 items-center self-stretch p-3 my-auto bg-lime-50 rounded-lg border border-lime-100 border-solid h-[58px] w-[58px]"
            aria-label="Next testimonial"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f5b2501245b621e326a517dad2d470fd4179b07b1a996b6425435d856ce677bf?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
              alt=""
              className="object-contain aspect-square w-[34px]"
            />
          </button>
        </div>
      </div>
    </section>
  );
};

export default TestimonialsSection;
