/**
 * This code was generated by Builder.io
 */
import React from "react";

const JoinTeam: React.FC = () => {
  return (
    <section className="flex overflow-hidden flex-col self-center p-10 mt-12 w-full bg-lime-50 rounded-xl border border-lime-100 border-solid max-w-[358px] max-md:px-5 max-md:mt-10">
      <div className="flex flex-col w-full text-center">
        <h2 className="text-2xl font-semibold text-neutral-800">
          Join Our Team
        </h2>
        <p className="mt-2.5 text-sm font-medium leading-5 text-zinc-800">
          We are always on the lookout for talented individuals who are
          enthusiastic about making a difference. Explore our career
          opportunities and join us in our mission to help people achieve their
          health and wellness goals.
        </p>
      </div>
      <button className="gap-2 self-stretch px-5 py-3.5 mt-5 w-full text-sm font-semibold bg-lime-300 rounded-md text-neutral-800">
        Apply Now
      </button>
    </section>
  );
};

export default JoinTeam;
