/**
 * This code was generated by Builder.io
 */
import React from "react";

const teamMembers = [
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/c3d4d7f48d02037d2992737784265ccc26913741825f66f967cf76af12544576?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
    alt: "Team member 1",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/ca571c55c486944ad274e950a378dd41550d00b5de2348c7553e4b26df34f3e0?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
    alt: "Team member 2",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/694e0fa8adce14af5678b21536adcd1b47f9780280efcd22dbba8f852bf0b281?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
    alt: "Team member 3",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/0560de4c495ef571f6a2450e436b6814aad45641c9bac57c138370d542baed77?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
    alt: "Team member 4",
  },
];

const TeamMembers: React.FC = () => {
  return (
    <div className="flex flex-col px-4 mt-8 w-full">
      {teamMembers.map((member, index) => (
        <img
          key={index}
          loading="lazy"
          src={member.src}
          alt={member.alt}
          className={`object-contain w-full aspect-[0.79] ${
            index > 0 ? "mt-5" : ""
          }`}
        />
      ))}
    </div>
  );
};

export default TeamMembers;
