/**
 * This code was generated by Builder.io
 */
import React from "react";

const TeamIntro: React.FC = () => {
  return (
    <section className="flex flex-col self-center mt-12 w-full max-w-[358px] max-md:mt-10">
      <div className="flex overflow-hidden flex-col p-8 w-full bg-lime-50 rounded-xl border border-lime-100 border-solid max-md:px-5">
        <div className="flex overflow-hidden relative flex-col gap-2.5 items-center self-center p-3.5 rounded-xl border-white border-solid aspect-square w-[62px]">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/3ffa4353affaa22eda155ad21ebc4f52349795a0600e1099c6d79f48ebb8e8f4?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
            alt=""
            className="object-cover absolute inset-0 size-full"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/00cc8792d54d5a2d5e802fce570365fe452d050e80728dc477549b19d971d315?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
            alt="Team icon"
            className="object-contain self-stretch my-auto rounded-none aspect-square w-[34px]"
          />
        </div>
        <div className="flex flex-col mt-8 w-full text-center">
          <h1 className="text-3xl font-semibold leading-10 text-neutral-800">
            Meet Our Team of Experts
          </h1>
          <p className="mt-1.5 text-sm font-medium leading-5 text-zinc-800">
            Our team at Nutritionist is composed of highly skilled professionals
            who are passionate about helping you achieve your health and
            wellness goals. With a diverse range of expertise in nutrition,
            coaching, and support, our team is dedicated to providing you with
            the guidance and personalized care you need. Get to know the experts
            behind our success and discover how they can make a positive impact
            on your journey to better health.
          </p>
        </div>
      </div>
    </section>
  );
};

export default TeamIntro;
