/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import TeamIntro from "./TeamIntro";
import TeamTabs from "./TeamTabs";
import TeamMembers from "./TeamMembers";
import JoinTeam from "./JoinTeam";
import Footer from "./Footer";

const TeamPage: React.FC = () => {
  return (
    <div className="flex flex-col items-start px-20 mx-auto w-full max-w-[480px] max-md:pl-5">
      <div className="flex overflow-hidden flex-col justify-center bg-stone-50">
        <Header />
        <main>
          <TeamIntro />
          <section className="flex flex-col w-full">
            <TeamTabs />
            <TeamMembers />
          </section>
          <JoinTeam />
        </main>
        <Footer />
      </div>
    </div>
  );
};

export default TeamPage;
