/**
 * This code was generated by Builder.io
 */
import React from "react";

const tabs = [
  "Management Team",
  "Nutritionists and Dietitians",
  "Customer Support",
  "Marketing and Communications",
  "Technology and Development",
];

const TeamTabs: React.FC = () => {
  return (
    <div className="flex overflow-hidden gap-5 items-center py-5 pl-5 w-full text-sm font-semibold bg-green-900 rounded-none text-neutral-200">
      {tabs.map((tab, index) => (
        <button
          key={index}
          className={`self-stretch my-auto ${
            index === 0
              ? "px-5 py-3 text-white bg-gray-700 rounded-md border border-gray-600 border-solid"
              : ""
          }`}
        >
          {tab}
        </button>
      ))}
    </div>
  );
};

export default TeamTabs;
