/**
 * This code was generated by Builder.io
 */
import React from "react";
import { AchievementCardProps } from "./types";

const AchievementCard: React.FC<AchievementCardProps> = ({
  icon,
  title,
  description,
}) => (
  <div className="flex flex-col p-8 mt-5 w-full bg-lime-50 rounded-xl border border-lime-100 border-solid max-md:px-5">
    <div className="flex gap-2.5 items-center w-full">
      <div className="flex gap-2.5 items-center self-stretch p-3 my-auto w-12 h-12 bg-lime-300 rounded-md">
        <img
          loading="lazy"
          src={icon}
          alt=""
          className="object-contain w-6 aspect-square"
        />
      </div>
      <h3 className="flex-1 shrink self-stretch my-auto text-lg font-semibold basis-6 text-neutral-800">
        {title}
      </h3>
    </div>
    <p className="mt-4 text-sm font-medium leading-5 text-zinc-800">
      {description}
    </p>
  </div>
);

export default AchievementCard;
