/**
 * This code was generated by Builder.io
 */
import React from "react";

interface AchievementCardProps {
  icon: string;
  title: string;
  description: string;
}

const AchievementCard: React.FC<AchievementCardProps> = ({
  icon,
  title,
  description,
}) => (
  <div className="flex flex-col p-8 mt-5 w-full bg-lime-50 rounded-xl border border-lime-100 border-solid max-md:px-5">
    <div className="flex gap-2.5 items-center w-full">
      <div className="flex gap-2.5 items-center self-stretch p-3 my-auto w-12 h-12 bg-lime-300 rounded-md">
        <img
          loading="lazy"
          src={icon}
          alt=""
          className="object-contain w-6 aspect-square"
        />
      </div>
      <h3 className="flex-1 shrink self-stretch my-auto text-lg font-semibold basis-6 text-neutral-800">
        {title}
      </h3>
    </div>
    <p className="mt-4 text-sm font-medium leading-5 text-zinc-800">
      {description}
    </p>
  </div>
);

const AchievementsSection: React.FC = () => {
  const achievements = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/0b77f0499e8041080dd4b411f3d439a9fdcc1d94918e9d72aa4683c71eecb903?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      title: "10,000+ Transformations",
      description:
        "Our personalized nutrition plans have helped thousands of individuals reach their weight loss goals and maintain a healthy lifestyle.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/f527116ba2b841307360da5a6180b2a0c1ba447d5fba51a592992bfabdd427a6?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      title: "Recognition for Excellence",
      description:
        "Nutritionist has been recognized as a leading provider of personalized nutrition coaching, receiving accolades for our innovative approach and commitment to client success.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/71a731a3714bcdf7439dfcebd5eccb5279c30f8046c706b1c4824caab40d5533?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      title: "Positive Client Reviews",
      description:
        "We have received numerous testimonials from satisfied clients who have experienced significant improvements in their health, weight, and overall well-being through our coaching program.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/d2f6833f3f912af29461f5fa86ff59839cacd13b62a5c24bca864a1bd86efaa7?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
      title: "Collaborate With Top Health Experts",
      description:
        "Nutritionist has established partnerships with respected nutritionists, dietitians, and health experts to ensure that our clients receive the highest quality guidance and support.",
    },
  ];

  return (
    <section className="flex flex-col mt-12 w-full max-w-[357px] max-md:mt-10">
      <div className="flex flex-col w-full text-center">
        <h2 className="text-3xl font-semibold text-neutral-800">
          Company Achievements
        </h2>
        <p className="mt-2 text-sm font-medium leading-5 text-zinc-800">
          At Nutritionist, we take pride in our accomplishments and the positive
          impact we have made on the lives of our clients. Here are some of our
          notable achievements
        </p>
      </div>
      <div className="flex flex-col mt-12 w-full max-md:mt-10">
        {achievements.map((achievement, index) => (
          <AchievementCard
            key={index}
            icon={achievement.icon}
            title={achievement.title}
            description={achievement.description}
          />
        ))}
      </div>
    </section>
  );
};

export default AchievementsSection;
