/**
 * This code was generated by Builder.io
 */
import { NavItem, AchievementCardProps } from "./types";

export const NAV_ITEMS: NavItem[] = [
  { label: "Home", href: "#home" },
  { label: "About", href: "#about" },
  { label: "Team", href: "#team" },
  { label: "Process", href: "#process" },
  { label: "Pricing", href: "#pricing" },
  { label: "Blog", href: "#blog" },
  { label: "Contact", href: "#contact" },
];

export const ACHIEVEMENTS: AchievementCardProps[] = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/0b77f0499e8041080dd4b411f3d439a9fdcc1d94918e9d72aa4683c71eecb903?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
    title: "10,000+ Transformations",
    description:
      "Our personalized nutrition plans have helped thousands of individuals reach their weight loss goals and maintain a healthy lifestyle.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/f527116ba2b841307360da5a6180b2a0c1ba447d5fba51a592992bfabdd427a6?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
    title: "Recognition for Excellence",
    description:
      "Nutritionist has been recognized as a leading provider of personalized nutrition coaching, receiving accolades for our innovative approach and commitment to client success.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/71a731a3714bcdf7439dfcebd5eccb5279c30f8046c706b1c4824caab40d5533?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
    title: "Positive Client Reviews",
    description:
      "We have received numerous testimonials from satisfied clients who have experienced significant improvements in their health, weight, and overall well-being through our coaching program.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/d2f6833f3f912af29461f5fa86ff59839cacd13b62a5c24bca864a1bd86efaa7?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
    title: "Collaborate With Top Health Experts",
    description:
      "Nutritionist has established partnerships with respected nutritionists, dietitians, and health experts to ensure that our clients receive the highest quality guidance and support.",
  },
];
