/**
 * This code was generated by Builder.io
 */
import React from "react";

const CTASection: React.FC = () => {
  return (
    <section className="flex overflow-hidden flex-col p-10 mt-12 w-full bg-lime-50 rounded-xl border border-lime-100 border-solid max-w-[358px] max-md:px-5 max-md:mt-10">
      <div className="flex flex-col w-full text-center">
        <h2 className="text-2xl font-semibold leading-8 text-neutral-800">
          We Are Proud of Our Achievements
        </h2>
        <p className="mt-2.5 text-sm font-medium leading-5 text-zinc-800">
          But our ultimate satisfaction comes from seeing our clients achieve
          their goals and live healthier, happier lives. Join Nutritionist today
          and embark on your own transformative journey towards optimal health
          and well-being.
        </p>
      </div>
      <button className="gap-2 self-stretch px-5 py-3.5 mt-5 w-full text-sm font-semibold bg-lime-300 rounded-md text-neutral-800">
        Book a Demo
      </button>
    </section>
  );
};

export default CTASection;
