/**
 * This code was generated by Builder.io
 */
import React from "react";

const OurStorySection: React.FC = () => {
  return (
    <section className="flex flex-col mt-12 w-full max-w-[358px] max-md:mt-10">
      <div className="flex flex-col w-full text-center">
        <h2 className="text-3xl font-bold text-neutral-800">Our Story</h2>
        <p className="mt-1.5 text-sm font-medium leading-5 text-zinc-800">
          Welcome to Nutritionist, your partner in achieving optimal health
          through personalized nutrition coaching. Our certified nutritionists
          are here to guide you on your weight loss journey.
        </p>
      </div>
      <div className="flex overflow-hidden flex-col mt-12 w-full rounded-xl border border-lime-100 border-solid max-md:mt-10">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/2cb9517dae141f43c6cc34c7b225ccbb3aa5161469a6bd5303fc179e38ac6ea1?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
          alt="Nutritionist story image 1"
          className="object-contain w-full aspect-[0.66]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/fa2682c5027610ed4239a730bceb91c4e785078ff4290eb856593251fcf1716a?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
          alt="Nutritionist story image 2"
          className="object-contain w-full aspect-[0.71]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0587dd91e9b16945b8a18116afa4d3865fa095bc046cf982e09a4b3cbbebd395?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
          alt="Nutritionist story image 3"
          className="object-contain w-full aspect-[0.71]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b5e84b6fd65396a5ac0048f6038799905c103f13c8e5615d85d526630af78c1d?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
          alt="Nutritionist story image 4"
          className="object-contain w-full aspect-[0.71]"
        />
      </div>
    </section>
  );
};

export default OurStorySection;
