/**
 * This code was generated by Builder.io
 */
export interface AchievementCardProps {
  icon: string;
  title: string;
  description: string;
}

export interface NavItem {
  label: string;
  href: string;
}
