/**
 * This code was generated by Builder.io
 */
import React from "react";

const WelcomeSection: React.FC = () => {
  return (
    <section className="flex flex-col items-center w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/a6bbca6a97e1c0cd9d97466e1ef215c05ec3b51bd80c50264fb82541e4ec4fca?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
        alt="Welcome to Nutritionist"
        className="object-contain mt-8 w-full aspect-[2.6] max-w-[358px]"
      />
      <div className="flex flex-col p-8 mt-12 w-full text-center bg-lime-50 rounded-xl border border-lime-100 border-solid max-w-[358px] max-md:px-5 max-md:mt-10">
        <h1 className="text-3xl font-semibold text-neutral-800">
          Welcome to Nutritionist
        </h1>
        <p className="mt-5 text-sm font-medium leading-5 text-zinc-800">
          Your trusted source for personalized nutrition coaching. Our mission
          is to help you achieve your weight loss and health goals through
          tailored nutrition plans and expert guidance. We understand that every
          individual is unique, and that's why we believe in providing
          personalized solutions that fit your lifestyle and preferences.
          <br />
          <br />
          With our team of qualified nutritionists and dietitians, we are
          dedicated to empowering you with the knowledge and tools you need to
          make lasting changes. Whether you want to shed those extra pounds,
          improve your overall well-being, or develop a healthier relationship
          with food, we are here to support you every step of the way.
          <br />
          <br />
          At Nutritionist, we believe that healthy eating should be enjoyable
          and sustainable. We emphasize the importance of balanced nutrition,
          focusing on whole foods and mindful eating practices. Our approach is
          rooted in scientific research and evidence-based strategies, ensuring
          that you receive the most up-to-date and accurate information.
          <br />
          <br />
          Join our community of individuals committed to transforming their
          lives through nutrition. Take control of your health, boost your
          energy levels, and discover the joy of nourishing your body with
          wholesome foods. We are here to guide you towards a healthier, happier
          you.
        </p>
      </div>
    </section>
  );
};

export default WelcomeSection;
