/**
 * This code was generated by Builder.io
 */
import React from "react";

interface BlogCardProps {
  category: string;
  image: string;
  title: string;
  description: string;
}

const BlogCard: React.FC<BlogCardProps> = ({
  category,
  image,
  title,
  description,
}) => {
  return (
    <article className="flex flex-col w-full bg-lime-50">
      <div className="flex flex-col px-8 pt-8 w-full">
        <h2 className="gap-2.5 self-start py-2 text-xl font-semibold border-solid border-b-[3px] border-b-lime-300 text-zinc-800">
          {category}
        </h2>
        <div className="flex flex-col pl-9 mt-8 w-full">
          <img
            loading="lazy"
            src={image}
            alt={title}
            className="object-contain w-full rounded-xl aspect-[2]"
          />
        </div>
      </div>
      <hr className="w-full bg-lime-100 border border-lime-100 border-solid min-h-[1px]" />
      <div className="flex flex-col justify-center p-8 w-full">
        <div className="flex flex-col w-full">
          <h3 className="text-lg font-semibold leading-7 text-neutral-800">
            {title}
          </h3>
          <p className="mt-2 text-base font-medium leading-6 text-zinc-800">
            {description}
          </p>
        </div>
        <button className="gap-2 self-start px-5 py-3.5 mt-6 text-sm font-semibold bg-lime-300 rounded-md text-neutral-800">
          Read More
        </button>
      </div>
    </article>
  );
};

export default BlogCard;
