/**
 * This code was generated by Builder.io
 */
import React from "react";
import BlogCard from "./BlogCard";

interface BlogPost {
  id: number;
  category: string;
  image: string;
  title: string;
  description: string;
}

const blogPosts: BlogPost[] = [
  {
    id: 1,
    category: "Weight Loss Tips",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/5b2ccdad94dc4bc614c026d84c77b8b2047e56220b58293f745043233dc4358c?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
    title: "10 Effective Strategies for Sustainable Weight Loss",
    description:
      "Discover proven strategies for long-term weight loss success. Learn how to create healthy habits, set achievable goals, and make sustainable lifestyle changes.",
  },
  {
    id: 2,
    category: "Weight Loss Tips",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/1e6aa8100ec105755fd3dcb0c38704a2582833946b371a60c74a9f5fc8129db1?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
    title: "The Role of Portion Control in Weight Management",
    description:
      "Learn how portion control can help you manage your weight effectively. Find practical tips for controlling portion sizes and avoiding overeating.",
  },
  {
    id: 3,
    category: "Weight Loss Tips",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/87e6c63d002021be2469f30c71a0d19228369e7c4045f94f86e5f8375318740c?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
    title: "Understanding Emotional Eating and How to Overcome It",
    description:
      "Explore the connection between emotions and eating habits. Get valuable insights on how to identify emotional triggers and develop healthier coping mechanisms.",
  },
  {
    id: 4,
    category: "Weight Loss Tips",
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/8d32d13c311b829eb8ab0724d9e2b6c34c1937a9e5151ab6998b460e88a42e9f?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b",
    title: "How to Stay Motivated on Your Weight Loss Journey",
    description:
      "Find effective strategies to stay motivated and overcome obstacles during your weight loss journey. Get tips on setting realistic goals, tracking progress, and celebrating achievements.",
  },
];

const BlogContent: React.FC = () => {
  return (
    <main className="flex flex-col self-center mt-12 w-full max-w-[358px]">
      <section className="flex overflow-hidden flex-col p-8 w-full bg-lime-50 rounded-xl border border-lime-100 border-solid">
        <div className="flex overflow-hidden relative flex-col gap-2.5 items-center self-center p-3.5 rounded-xl border-white border-solid aspect-square border-[3px] w-[62px]">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/3ffa4353affaa22eda155ad21ebc4f52349795a0600e1099c6d79f48ebb8e8f4?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
            alt=""
            className="object-cover absolute inset-0 size-full"
            aria-hidden="true"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/96c2b247127c04b7f747fd2835ee196763d12e679fe6585e3c110f6a4660b94d?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
            alt="Blog icon"
            className="object-contain self-stretch my-auto rounded-none aspect-square w-[34px]"
          />
        </div>
        <div className="flex flex-col mt-8 w-full text-center">
          <h1 className="text-3xl font-semibold text-neutral-800">Our Blogs</h1>
          <p className="mt-1.5 text-sm font-medium leading-5 text-zinc-800">
            Welcome to the Blog section of Nutritionist, your trusted source for
            insightful articles, tips, and expert advice on nutrition and
            wellness. Here, we strive to provide you with engaging and
            informative content that will inspire and empower you to make
            informed decisions about your health. Explore our blog to discover a
            wealth of resources that cover a wide range of topics related to
            nutrition, fitness, and overall well-being.
          </p>
        </div>
      </section>
      <nav className="flex gap-5 items-center py-5 pl-5 w-full text-sm font-semibold bg-green-900 rounded-none text-neutral-200">
        <button className="self-stretch px-5 py-3 my-auto text-white whitespace-nowrap bg-gray-700 rounded-md border border-gray-600 border-solid">
          All
        </button>
        <button className="self-stretch my-auto">Weight Loss Tips</button>
        <button className="self-stretch my-auto">Healthy Eating</button>
        <button className="self-stretch my-auto">Fitness and Exercise</button>
      </nav>
      <div className="flex overflow-hidden flex-col mt-8 w-full rounded-xl border border-lime-100 border-solid">
        {blogPosts.map((post) => (
          <BlogCard key={post.id} {...post} />
        ))}
      </div>
    </main>
  );
};

export default BlogContent;
