/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import BlogContent from "./BlogContent";
import Footer from "./Footer";

const BlogPage: React.FC = () => {
  return (
    <div className="flex flex-col px-3.5 mx-auto w-full max-w-[480px]">
      <div className="flex overflow-hidden flex-col justify-center bg-stone-50">
        <Header />
        <BlogContent />
        <Footer />
      </div>
    </div>
  );
};

export default BlogPage;
