/**
 * This code was generated by Builder.io
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <footer className="flex flex-col px-4 py-8 mt-12 border-t border-solid bg-zinc-800 border-t-neutral-800">
      <div className="flex flex-col w-full">
        <div className="flex gap-10 justify-between items-center w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ccaf9dd39a7131b47d430c18c8020e9efeb6f0574dcd51126760da2e5c5294b3?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
            alt="Nutritionist Logo"
            className="object-contain shrink-0 self-stretch my-auto aspect-[4.33] w-[130px]"
          />
          <div className="flex gap-1.5 items-center self-stretch my-auto rounded-xl">
            <span className="self-stretch my-auto text-base font-semibold text-white">
              Go To Top
            </span>
            <button
              className="flex flex-col justify-center items-center self-stretch px-3 my-auto w-12 h-12 bg-green-900 rounded-[73px]"
              aria-label="Scroll to top"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/863729e8bdb9fbd128a12546487b62cc04908b7ef6ae1d7a8671faecf4fe33a0?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
                alt=""
                className="object-contain w-6 aspect-square"
                aria-hidden="true"
              />
            </button>
          </div>
        </div>
        <nav className="flex gap-4 items-center pr-16 mt-5 w-full text-sm font-semibold text-white whitespace-nowrap">
          <a href="#" className="self-stretch my-auto">
            Home
          </a>
          <a href="#" className="self-stretch my-auto">
            About
          </a>
          <a href="#" className="self-stretch my-auto">
            Team
          </a>
          <a href="#" className="self-stretch my-auto">
            Process
          </a>
          <a href="#" className="self-stretch my-auto">
            Pricing
          </a>
          <a href="#" className="self-stretch my-auto">
            Blog
          </a>
          <a href="#" className="self-stretch my-auto">
            Contact
          </a>
        </nav>
      </div>
      <div className="flex flex-col p-5 mt-8 w-full bg-green-900 rounded-lg border border-gray-700 border-solid">
        <div className="flex flex-col w-full text-base font-medium text-white">
          <a
            href="mailto:hello@squareup.com"
            className="flex gap-1 justify-center items-center p-3 w-full whitespace-nowrap rounded border border-gray-700 border-solid"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0c3b8e966c872940cd6ffa6b29084922499518061cf11579c341ba7f787a3f6b?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
              aria-hidden="true"
            />
            <span className="self-stretch my-auto">hello@squareup.com</span>
          </a>
          <a
            href="tel:+9191813232309"
            className="flex gap-1 justify-center items-center p-3 mt-4 w-full rounded border border-gray-700 border-solid"
          >
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/2759ee4d9215ec45d27e8a1bc9a26353f6b971b17d107141e097ef87685a0f82?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
              aria-hidden="true"
            />
            <span className="self-stretch my-auto">+91 91813 23 2309</span>
          </a>
          <address className="flex gap-1 justify-center items-center p-3 mt-4 w-full rounded border border-gray-700 border-solid not-italic">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/4455bd867858521c1e49d8a30654e3145fab82951062f65ec4b807481f4be81d?placeholderIfAbsent=true&apiKey=a54b75d57d8041fca68d2ad49ee3043b"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
              aria-hidden="true"
            />
            <span className="self-stretch my-auto">Somewhere in the World</span>
          </address>
        </div>
        <p className="self-center mt-5 text-sm text-zinc-100">
          © 2023 Nutritionist. All rights reserved.
        </p>
      </div>
    </footer>
  );
};

export default Footer;
